{% set name = "nbclient" %}
{% set version = "0.10.1" %}
{% set build = 1 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3e93e348ab27e712acd46fccd809139e356eb9a31aab641d1a7991a6eb4e6f68

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - nbformat >=5.1
    - traitlets >=5.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbclient

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  dev_url: https://github.com/jupyter/nbclient
  doc_url: https://nbclient.readthedocs.io
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs

extra:
  recipe-maintainers:
    - davidbrochart
