{% set name = "nbclient" %}
{% set version = "0.6.1" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a6d7049f640bb79c795691bb29ab7ed00ee83c447cb6ac561cf4e171fefb6462

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - traitlets >=5.0.0
    - jupyter_client >=6.1.5
    - nbformat >=5.0
    - nest-asyncio

test:
  imports:
    - nbclient

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A client library for executing notebooks. Formally nbconvert's ExecutePreprocessor.
  description: |
    NBClient is a tool for parameterizing and executing Jupyter Notebooks.
    NBClient lets you execute notebooks. Similar in nature to jupyter_client, as the jupyter_client
    is to the jupyter protocol nbclient is to notebooks allowing for execution contexts to be run.
  dev_url: https://github.com/jupyter/nbclient
  doc_url: https://nbclient.readthedocs.io
  doc_source_url: https://github.com/jupyter/nbclient/tree/master/docs

extra:
  recipe-maintainers:
    - davidbrochart
